---
- name: Configure and install vnc-server
  tags: [vnc]
  ansible.builtin.import_tasks: vnc.yml
  notify: restart lightdm

- name: Configure and install websockify
  tags: [websockify]
  ansible.builtin.import_tasks: websockify.yml
