---
- name: Vnc server packages
  become: true
  ansible.builtin.apt:
    name: "{{ vnc_server_packages }}"
    state: present

- name: Configure lightdm-vnc
  become: true
  ansible.builtin.template:
    src: "{{ lightdm_vnc_config_template }}"
    dest: /etc/lightdm/lightdm.conf.d/vnc.conf
    mode: "0644"

- name: Configure lightdm-xdmcp
  become: true
  ansible.builtin.template:
    src: "{{ lightdm_xdmcp_config_template }}"
    dest: /etc/lightdm/lightdm.conf.d/xdmcp.conf
    mode: "0644"

- name: Configure lightdm users
  become: true
  ansible.builtin.template:
    src: "{{ lightdm_users_config_template }}"
    dest: /etc/lightdm/users.conf
    mode: "0644"

- name: Configure Accountservice users
  become: true
  notify: Restart Accounts Service
  ansible.builtin.copy:
    src: accountservice-systemuser
    dest: /var/lib/AccountsService/users/{{ item }}
    mode: "0600"
  loop: "{{ lightdm_hidden_users }}"

- name: Copy securetty
  become: true
  when: ansible_distribution_version == "22.04"
  ansible.builtin.copy:
    remote_src: true
    src: /usr/share/doc/util-linux/examples/securetty
    dest: /etc/securetty
    mode: "0644"

- name: Remove kwallet from pam.d/lightdm*
  become: true
  ansible.builtin.lineinfile:
    path: /etc/pam.d/{{ item }}
    state: absent
    regexp: ^(.*)pam_kwallet(\d?).so(.*)$
  loop: [lightdm, lightdm-autologin, lightdm-greeter]
- name: Copy dbus ibus to dbus local
  become: true
  notify: Update dconf
  ansible.builtin.copy:
    src: /etc/dconf/db/ibus
    dest: /etc/dconf/db/local
    mode: "0644"
    remote_src: true

- name: Copy dbus ibus to dbus local
  become: true
  notify: Update dconf
  ansible.builtin.copy:
    content: |
      user-db:user
      system-db:ibus
      system-db:local
    dest: /etc/dconf/profile/ibus
    mode: "0644"

- name: Copy dbus ibus to dbus local
  become: true
  ansible.builtin.copy:
    src: 80mate-environment
    dest: /etc/X11/Xsession.d/80mate-environment
    mode: "0644"
