---
- name: vnc server packages
  ansible.builtin.apt:
    name: "{{ vnc_server_packages }}"
    state: present
  become: true

- name: configure lightdm-vnc
  ansible.builtin.template:
    src: "{{ lightdm_vnc_config_template }}"
    dest: "/etc/lightdm/lightdm.conf.d/vnc.conf"
    mode: "0644"
  become: true

- name: configure lightdm-xdmcp
  ansible.builtin.template:
    src: "{{ lightdm_xdmcp_config_template }}"
    dest: "/etc/lightdm/lightdm.conf.d/xdmcp.conf"
    mode: "0644"
  become: true

- name: configure lightdm users
  ansible.builtin.template:
    src: "{{ lightdm_users_config_template }}"
    dest: "/etc/lightdm/users.conf"
    mode: "0644"
  become: true

- name: configure Accountservice users
  ansible.builtin.copy:
    src: "accountservice-systemuser"
    dest: "/var/lib/AccountsService/users/{{ item }}"
    mode: "0600"
  become: true
  notify: restart Accounts Service
  loop: "{{ lightdm_hidden_users }}"

- name: Copy securetty
  ansible.builtin.copy:
    remote_src: true
    src: /usr/share/doc/util-linux/examples/securetty
    dest: /etc/securetty
    mode: 0644
  become: true

- name: Remove kwallet from pam.d/lightdm*
  ansible.builtin.lineinfile:
    path: "/etc/pam.d/{{ item }}"
    state: absent
    regexp: '^(.*)pam_kwallet(\d?).so(.*)$'
  become: true
  loop: ["lightdm", "lightdm-autologin", "lightdm-greeter"]

- name: Copy dbus ibus to dbus local
  ansible.builtin.copy:
    src: "/etc/dconf/db/ibus"
    dest: "/etc/dconf/db/local"
    mode: 0644
    remote_src: true
  notify: Update dconf
  become: true

- name: Copy dbus ibus to dbus local
  ansible.builtin.copy:
    content: |
      user-db:user
      system-db:ibus
      system-db:local
    dest: "/etc/dconf/profile/ibus"
    mode: 0644
  notify: Update dconf
  become: true
