---
- name: Download websockify
  ansible.builtin.get_url:
    url: "https://github.com/b3n4kh/websockify-go/releases/download/{{ websockify_version }}/websockify-go"
    dest: /usr/local/bin/websockify-go
    mode: "0755"
  become: true


- name: configure websockify
  ansible.builtin.template:
    src: "{{ websockify_service_template }}"
    dest: "/etc/systemd/system/websockify.service"
    mode: "0644"
  become: true

- name: Start websockify service
  ansible.builtin.systemd:
    name: websockify
    enabled: true
    state: started
    daemon_reload: true
  become: true
