---
- name: restart lightdm
  become: true
  ansible.builtin.service:
    name: lightdm
    state: restarted

- name: restart Accounts Service
  become: true
  ansible.builtin.service:
    name: accounts-daemon
    state: restarted

- name: Update dconf
  become: true
  ansible.builtin.command: "dconf update"
