---
- name: restart lightdm
  become: true
  service:
    name: lightdm
    state: restarted

- name: restart Accounts Service
  become: true
  service:
    name: accounts-daemon
    state: restarted

- name: Update dconf
  become: true
  command: "dconf update"
